/// Central error type for the WaveBranch VCS.
///
/// All modules propagate errors upward through this enum, ensuring
/// a single, consistent error boundary at the CLI layer. Each variant
/// captures the exact failure domain so callers can pattern-match on
/// specific failure modes without inspecting opaque strings.
use thiserror::Error;

#[derive(Debug, Error)]
pub enum WaveBranchError {
    /// Transparent wrapper around `std::io::Error`.
    ///
    /// Any filesystem operation (create_dir, write, read) that fails
    /// will automatically convert into this variant via the `From` impl
    /// generated by `#[from]`.
    #[error(transparent)]
    IoError(#[from] std::io::Error),

    /// Raised by `wave init` when `.wavebranch/` already exists in the
    /// current working directory. Prevents accidental re-initialization
    /// that could corrupt an existing DAG.
    #[error("WaveBranch repository already exists in this directory")]
    RepoAlreadyExists,

    /// Raised when a command requires a valid repository context but no
    /// `.wavebranch/` directory is found in the current or ancestor dirs.
    #[error("Not a WaveBranch repository (or any parent up to mount point)")]
    #[allow(dead_code)]
    RepoNotFound,

    /// Raised when `hound` cannot parse the target file as a valid WAV.
    /// Carries the underlying parse error message for diagnostics.
    #[error("Invalid WAV format: {0}")]
    InvalidWavFormat(String),

    /// Raised when `flate2` Zlib compression or decompression fails.
    #[error("Compression error: {0}")]
    CompressionError(String),
    #[error("Object error: {0}")]
    ObjectError(String),
    #[error("Audio error: {0}")]
    AudioError(String),
    #[error("Index error: {0}")]
    IndexError(String),
    #[error("Path error: {0}")]
    PathError(String),
    #[error("Network error: {0}")]
    NetworkError(String),

    /// Raised when `read_blob` cannot find the object file for a given hash.
    #[error("Object not found: {0}")]
    #[allow(dead_code)]
    ObjectNotFound(String),

    /// Raised when serde_json serialization or deserialization fails.
    #[error("Serialization error: {0}")]
    SerializationError(#[from] serde_json::Error),
}
